title:             P覺nar Akyaz覺
email:             pinar.akyazi@epfl.ch
description:       PhD Student, living the life.
author:            P覺nar Akyaz覺
url:               https://pinarakyazi.github.io
baseurl:           /home
theme:             jekyll-theme-awesome
# Social Profiles
github_username:   pinarakyazi

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
